name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: Deploy back-to-back free distribution of ixia-c
        run: |
          ./do.sh create_ixia_c_b2b_free
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Run go tests
        run: |
          ./do.sh gotest
      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: generated-artifacts
          path: |
            logs
      - name: Teardown back-to-back free distribution of ixia-c
        run: |
          ./do.sh rm_ixia_c_b2b_free
